### PR TITLE
Remove space

### PR DESCRIPTION
**Pull request by Luyunmt**
Remove space

### CODE REVIEW

**Comment by jongio** [comment]
Does this impact tests or other project files?  Just want to make sure all tests pass with this change.  Thanks

**Comment by Luyunmt** [comment]
> Does this impact tests or other project files? Just want to make sure all tests pass with this change. Thanks

**Comment by Luyunmt** [comment]
run tests, all tests passed.

**Comment by jongio** [comment]
Thank you!

**Pull request merged**
